---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation
APPLY_FIXES: none
ENABLE_LINTERS:
  # GitHub Actions
  - ACTION_ACTIONLINT

  # JSON
  - JSON_JSONLINT
  - JSON_PRETTIER

  # Markdown
  - MARKDOWN_MARKDOWNLINT

  # Repository
  - REPOSITORY_TRIVY
  - REPOSITORY_GITLEAKS
  - REPOSITORY_CHECKOV

  # Terraform
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TERRAFORM_FMT
  - TERRAFORM_TFLINT

  # YAML
  - YAML_PRETTIER
  - YAML_YAMLLINT

DISABLE_ERRORS: false
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PARALLEL: true
GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true
VALIDATE_ALL_CODEBASE: false
LOG_LEVEL: INFO

# Markdown
MARKDOWN_MARKDOWN_LINK_CHECK_ARGUMENTS: "-q"

# Terraform
TERRAFORM_TERRASCAN_ARGUMENTS: "scan -d . -i terraform -v"

PLUGINS:
  - https://raw.githubusercontent.com/shiranr/linkcheck/v2.0.17.beta/mega-linter-plugin-linkcheck/linkcheck.megalinter-descriptor.yml
